In [20]:
import pandas as pd
df = pd.read_csv ("housing.csv")

In [21]:
# print (df.head())   it shows 5 first rows

In [22]:
print (df.shape)     

# it shows how amny rows and columns

(545, 13)

In [23]:
print (df.dtypes)

# it shows the data types of each column

price                 int64
area                  int64
bedrooms            float64
bathrooms             int64
stories               int64
mainroad             object
guestroom            object
basement             object
hotwaterheating      object
airconditioning      object
parking               int64
prefarea             object
furnishingstatus     object
dtype: object

In [24]:
print (df.info())

# it shows the summary and memory

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          541 non-null    float64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: float64(1), int64(5), object(7)
memory usage: 55.5+ KB
None

In [25]:
print (df.describe())

# it shows numeric data

              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  541.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.964880    1.286239    1.805505
std    1.870440e+06   2170.141023    0.740786    0.502470    0.867492
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000

          parking
count  545.000000
mean     0.693578
std      0.861586
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      3.000000

In [26]:
print (df ['furnishingstatus'].value_counts())

# it shows catagorical numbers that how many in each catagory

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [27]:
print (df['furnishingstatus'].unique(
    
))

['furnished' 'semi-furnished' 'unfurnished']

In [28]:
df.isnull().sum()

price               0
area                0
bedrooms            4
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [29]:
df



# it shows the database all

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4.0,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4.0,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3.0,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4.0,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4.0,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2.0,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3.0,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2.0,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3.0,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3.0,1,2,yes,no,no,no,no,0,no,unfurnished

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
print(df.dtypes)

price                 int64
area                  int64
bedrooms            float64
bathrooms             int64
stories               int64
mainroad             object
guestroom            object
basement             object
hotwaterheating      object
airconditioning      object
parking               int64
prefarea             object
furnishingstatus     object
dtype: object

In [32]:
df['price'] = df['price'].astype (float)

print (df.dtypes['price'])

# it changes the data types

float64

In [33]:
print (df.isnull().sum())

price               0
area                0
bedrooms            4
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [34]:
# now we have null data in bedroom column


df['bedrooms'] = df ['bedrooms'].fillna(df['bedrooms'].median(
    
))


df[['bedrooms']]

     bedrooms
0         4.0
1         4.0
2         3.0
3         4.0
4         4.0
..        ...
540       2.0
541       3.0
542       2.0
543       3.0
544       3.0

[545 rows x 1 columns]

In [ ]:
# Counts missing values in the price column
df ['bedrooms'] = df ['bedrooms'].fillna(df['bedrooms'].median())


# to fill the null cells with the median numbers of the bedrooms

In [ ]:
df.isnull().sum()


# all null in bedrooms column were filled

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64